# Generated by Django 2.1.7 on 2019-02-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('columns', models.PositiveIntegerField(default=0)),
                ('values', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
